### ISSUE TITLE
Set used in formalization is finite or infinite ?

### ISSUE THREAD

**Issue by mukeshtiwari** [JamesShaker/TCSReadingGroup#2]
Precisely this line ? 
val _ = type_abbrev("language", ``:sipser_string set``);
CC  @mn200 

Pardon me for my (open-ended) stupid question, and I even don't know if it is sensible question, but I am kind of landing into decidability problem.  I have defined a language as function from word (list of symbols) to Prop. Given any arbitrary language L, if there is automaton M which accept each word of this language then it's regular language, and it's not regular if I can't find any machine (possible infinite automaton) which recognizes it.  I am wondering if it's decidable or not [1].

  ```

    (*  Langauge is predicate over Prop *)
    Definition language := word -> Prop.

    
    (* a machine m recognizes a langauge l if machine accepts 
       every word in langauge *)
    Definition machine_recog_langauge (m : Automata) (l : language) :=
      forall w, l w  -> machine_accept m w = true.

    
    (* A language l is regular if there exists a machine which 
       recognizes it *)
    Definition regular_language (l : language) :=
      existsT (m : Automata), machine_recog_langauge m l.

    Definition not_regular_language (l : language) :=
      forall (m : Automata), ~machine_recog_langauge m l.

    Lemma regular_language_dec :
      forall (l : language), regular_language l +
                        not_regular_language l.


```
[1] https://en.wikipedia.org/wiki/Rice%27s_theorem

**Comment by JamesShaker** [comment]
Hi Mukesh,

A language is only regular if it is recognised by a **finite** automaton. In particular in the HOL definition part of the constraints on a well-formed finite automaton (a `wfFA`) includes having a finite set of states `Q` and a finite alphabet `A`. I believe that makes the problem decidable but I'm not entirely sure. Here's the complete `wfFA` condition on a general finite automaton record `a` (unfortunately we can't force well formed conditions on the base type!):

```
  wfFA a <=>
    FINITE a.Q ∧ (* or /\ *)
    FINITE a.A ∧
    a.C ⊆ a.Q ∧ (* or SUBSET *)
    a.q0 ∈ a.Q (* or IN *) ∧
    ∀ (* ! *) q c.
      c ∈ a.A ∧ q ∈ a.Q ⇒ (* ==> *) a.tf q c ∈ a.Q
    (* if you apply the transition function to a state in
       the machine's state set, and a character in the
       machine's alphabet, then you'd better stay in the
       set of machine states *)
```

**Comment by lxndrcx** [comment]
Sets in HOL can be infinite, depending on how they're defined. A set is just a function `'a -> bool`, so language is `sipser_string -> bool`.
